repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.9
  hooks:
    # Run the linter.
    - id: ruff
      entry: ruff check gaftools/ tests/ setup.py
    # Run the formatter.
    - id: ruff-format
      args: [gaftools/, tests/, setup.py]
